[project]
protostar-version = "0.9.1"
lib-path = "lib"
cairo-path = ["lib/cairo_contracts/src"]

[contracts]

ex01 = ["src/ex01.cairo"]
ex0456 = ["src/ex0456.cairo"]
ex0789 = ["src/ex0789.cairo"]
ex11 = ["src/ExerciseSolution.cairo"]
idtk = ["src/IDTKERC20.cairo"]
ex12 = ["src/ex12.cairo"]

